# Generated by Django 4.2.7 on 2023-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
