# Generated by Django 4.2.7 on 2023-11-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
